---
title: "Data Splitting Scenarios (v)"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results = 'hide'}
path = dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(path)
library(MASS) 
library(ggplot2)
library(glmnet)
library(ggthemes)
library(patchwork)
library(doSNOW)
library(foreach)
library(doParallel)
library(latex2exp)
cl <- makeCluster(8, outfile = 'outs.out')
registerDoParallel(cl)
registerDoSNOW(cl)
clusterEvalQ(cl = cl, RhpcBLASctl::blas_set_num_threads(1))

n = 400
q_fdr = 0.1
Rep_times = 200
seeds=54321

d_X = 1500
d_h1 = 30
d_h0 = d_X - d_h1
label_X1X2 = c(rep('Null', d_h0), rep('Non-null', d_h1))
Sigma = diag(1,d_X,d_X)
for (i in 1:d_X) {
  for (j in 1:d_X) {
    Sigma[i,j] = 0.5^abs(i-j)
  }
}

parameter_proportion = c(0.5,0.6,0.7,0.8,0.9,1)
names = c('5:5','6:4','7:3','8:2','9:1','1:0')
parameter_magnitude = c(0.25,0.4,0.55) 
names_mag = c('025','040','050')

output_table_fdr = data.frame(matrix(0,4*length(parameter_proportion),length(parameter_magnitude)))
output_table_power = data.frame(matrix(0,4*length(parameter_proportion),length(parameter_magnitude)))

DD_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
DD_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
S_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
S_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
SPlus_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
SPlus_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
Smin_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
Smin_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))

Output_fdr_power <- foreach (time = 1:Rep_times, .packages =c('MASS', 'glmnet')) %dopar%  {
  source('Functions.R')
  set.seed(time+seeds)
  print(Sys.time())
  X_matrix = mvrn(n, rep(0,d_X), Sigma)
  X_matrix = X_matrix[,sample(d_X)]
  n_index = sample(n,n/2)
  X_matrix1 = X_matrix[n_index,]
  X_matrix2 = X_matrix[setdiff(c(1:n), n_index),]
  M1 = get_M(X_matrix1)
  M2 = get_M(X_matrix2)
  e = rnorm(n,0,1)
  
  DD_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  DD_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  S_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  S_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  SPlus_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  SPlus_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  Smin_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  Smin_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  
  for (ii in 1:length(parameter_proportion)) {
    for (jj in 1:length(parameter_magnitude)) {
      negative = parameter_proportion[ii]
      positive = 1 - negative
      posi_len = round(positive*d_h1)
      nega_len = d_h1 - posi_len
      magnitude = parameter_magnitude[jj]
      c1 = rep(magnitude,round(posi_len))
      c2 = rep(-0.25,round(nega_len))
      coef_X = matrix(c(rep(0,d_h0), c1, c2), d_X) 
      
      Y = X_matrix %*% coef_X + e
      Y1 = Y[n_index,]
      Y2 = Y[setdiff(c(1:n), n_index),]
      
      cvfit <- cv.glmnet(X_matrix, Y, intercept = F, standardize = F)
      lambda <- cvfit$lambda.min*1.2
      beta1 <- as.vector(glmnet(X_matrix1, Y1, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
      beta2 <- as.vector(glmnet(X_matrix2, Y2, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
      index_beta1 = which(beta1 == 0)
      index_beta2 = which(beta2 == 0)
      
      beta1_d = as.numeric(beta1 + 2/n*M1%*%t(X_matrix1)%*%(Y1 - X_matrix1 %*% beta1))
      beta2_d = as.numeric(beta2 + 2/n*M2%*%t(X_matrix2)%*%(Y2 - X_matrix2 %*% beta2))
      
      sigma1 = sqrt(diag(M1%*%(t(X_matrix1)%*%diag(diag((Y1-X_matrix1%*%beta1)%*%t(Y1-X_matrix1%*%beta1)))%*%X_matrix1/(n/2))%*%t(M1)))
      sigma2 = sqrt(diag(M2%*%(t(X_matrix2)%*%diag(diag((Y2-X_matrix2%*%beta2)%*%t(Y2-X_matrix2%*%beta2)))%*%X_matrix2/(n/2))%*%t(M2)))
      
      X1 = beta1_d/sigma1
      X2 = beta2_d/sigma2
      
      index1 = intersect(which(X1>0),which(X2>0))
      index2 = intersect(which(X1<0),which(X2>0))
      index3 = intersect(which(X1<0),which(X2<0))
      index4 = intersect(which(X1>0),which(X2<0))
      
      X1_4444 = c(X1[c(index2,index4)])
      X2_4444 = c(X2[c(index2,index4)])
      
      h0 = 1.0*c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
      h1 = 1.4*c(bandwidth.nrd(X1), bandwidth.nrd(X2))
      
      Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
      f0_hat0 = function(x){
        return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
      }
      f0_hat = function(x){
        return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
      }
      
      Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
      f_hat = function(x){
        return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
      }
      
      Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
      lfdr_points_2 = rep(1,2*length(index2))
      lfdr_points_4 = rep(1,2*length(index4))
      lfdr_points13 = lfdr_points13 = rep(1,length(c(index1,index3)))
      lfdr_points13 = apply(cbind(X1[c(index1,index3)],X2[c(index1,index3)]), 1, Lfdr_hat13)
      lfdr_points_2= apply(cbind(c(X1[index2],-X1[index2]),c(-X2[index2], X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
      lfdr_points_4= apply(cbind(c(-X1[index4],X1[index4]),c(X2[index4], -X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
      
      get_localfdr_threshold_half <- function(lfdr13, lfdr2, lfdr4,q_fdr){
        t = sort(c(lfdr13,lfdr2,lfdr4))
        t[t==1]=0.9999
        Ta = sapply(t,function(x){(1+0.5*(length(lfdr4[lfdr4<=x]) + length(lfdr2[lfdr2<=x])))/max(1,length(lfdr13[lfdr13<=x]))})
        sh = max(t[which(Ta<q_fdr)]) 
        
        return(sh)
      }
      
      fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, q_fdr)
      label_X1X2_13 = label_X1X2[c(index1,index3)]
      number_d = length(which(lfdr_points13<fdr_q))
      number_td = length(intersect(which(lfdr_points13<fdr_q), which(label_X1X2_13 != 'Null')))
      
      get_conventional_threshold <- function(S, q_fdr){
        t = sort(abs(S))
        Ta = sapply(t,function(x){(1+length(S[S<(-x)]))/max(1,length(S[S>x]))})
        sh = min(t[which(Ta<q_fdr)])
        return(sh)
      }
      
      S_tol = X1*X2
      sh = get_conventional_threshold(S_tol,q_fdr)
      S_fdr = length(intersect(which(S_tol > sh), which(label_X1X2 == 'Null'))) / max(length(which(S_tol > sh)),1)
      S_power = length(intersect(which(S_tol > sh), which(label_X1X2 != 'Null'))) / (d_X - d_h0)
      
      SPlus_tol = sign(X1*X2)*(abs(X1) + abs(X2))
      sh = get_conventional_threshold(SPlus_tol,q_fdr)
      SPlus_fdr = length(intersect(which(SPlus_tol > sh), which(label_X1X2 == 'Null'))) / max(length(which(SPlus_tol > sh)),1)
      SPlus_power = length(intersect(which(SPlus_tol > sh), which(label_X1X2 != 'Null'))) / (d_X - d_h0)
      
      Smin_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
      sh = get_conventional_threshold(Smin_tol,q_fdr)
      Smin_fdr = length(intersect(which(Smin_tol > sh), which(label_X1X2 == 'Null'))) / max(length(which(Smin_tol > sh)),1)
      Smin_power = length(intersect(which(Smin_tol > sh), which(label_X1X2 != 'Null'))) / (d_X - d_h0)      
      
      DD_fdr = (number_d - number_td)/ max(1,number_d)
      DD_power = (number_td)/(d_X-d_h0)
      
      
      DD_fdr_matrix[ii,jj] = DD_fdr
      DD_power_matrix[ii,jj] = DD_power
      S_fdr_matrix[ii,jj] = S_fdr
      S_power_matrix[ii,jj] = S_power
      SPlus_fdr_matrix[ii,jj] = SPlus_fdr
      SPlus_power_matrix[ii,jj] = SPlus_power
      Smin_fdr_matrix[ii,jj] = Smin_fdr
      Smin_power_matrix[ii,jj] = Smin_power
    }
  }
  
  return(list(DD_fdr_matrix, DD_power_matrix, S_fdr_matrix, S_power_matrix, SPlus_fdr_matrix, SPlus_power_matrix, Smin_fdr_matrix, Smin_power_matrix))
}

for (i in 1:Rep_times) {
  DD_fdr_m  = DD_fdr_m + Output_fdr_power[[i]][[1]]/Rep_times
  DD_power_m  = DD_power_m + Output_fdr_power[[i]][[2]]/Rep_times
  S_fdr_m  = S_fdr_m + Output_fdr_power[[i]][[3]]/Rep_times
  S_power_m  = S_power_m + Output_fdr_power[[i]][[4]]/Rep_times
  SPlus_fdr_m  = SPlus_fdr_m + Output_fdr_power[[i]][[5]]/Rep_times
  SPlus_power_m  = SPlus_power_m + Output_fdr_power[[i]][[6]]/Rep_times
  Smin_fdr_m  = Smin_fdr_m + Output_fdr_power[[i]][[7]]/Rep_times
  Smin_power_m  = Smin_power_m + Output_fdr_power[[i]][[8]]/Rep_times
}

for (i in 1:length(parameter_magnitude)) {
  output_table_fdr[,i] = as.vector(t(cbind(DD_fdr_m[,i],S_fdr_m[,i],SPlus_fdr_m[,i],Smin_fdr_m[,i])))
  output_table_power[,i] = as.vector(t(cbind(DD_power_m[,i],S_power_m[,i],SPlus_power_m[,i],Smin_power_m[,i])))
}


appender <- function(string){TeX(paste("\\mu = $", string))}
plot_data1 = data.frame(Power = output_table_power[,1], FDR = output_table_fdr[,1], `Threshold` = rep(c('SAS', 'DM', 'DSA', 'DSM'), length(parameter_proportion)), `delta` = rep(factor(parameter_proportion, level = as.character(parameter_proportion)), each=4))
plot_data1$Threshold = factor(plot_data1$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))
colnames(plot_data1) = c('Power', 'FDR', 'Threshold', 'delta')
plot_data1$Scenario = 0.25
plot_data1$Threshold = factor(plot_data1$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))

Fig_power1 =  ggplot() +
  geom_point(data = plot_data1, aes(x = delta, y= Power, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data1, aes(x = delta, y= Power, group = Threshold,color = Threshold, linetype = Threshold)) +
  facet_wrap(~Scenario, labeller = as_labeller(appender, default = label_parsed))+
  xlab(element_blank()) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


Fig_FDR1 =  ggplot() +
  geom_point(data = plot_data1, aes(x = delta, y= FDR, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data1, aes(x = delta, y= FDR, group = Threshold,color = Threshold, linetype = Threshold)) +
  ylim(c(0,0.3)) +
  xlab(expression(delta)) +
  theme_bw() +
  geom_hline(yintercept = q_fdr, linetype='dashed', alpha=0.5) +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


plot_data2 = data.frame(Power = output_table_power[,2], FDR = output_table_fdr[,2], `Threshold` = rep(c('SAS', 'DM', 'DSA', 'DSM'), length(parameter_proportion)), `delta` = rep(factor(parameter_proportion, level = as.character(parameter_proportion)), each=4))
colnames(plot_data2) = c('Power', 'FDR', 'Threshold', 'delta')
plot_data2$Scenario = 0.4
plot_data2$Threshold = factor(plot_data2$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))
Fig_power2 =  ggplot() +
  geom_point(data = plot_data2, aes(x = delta, y= Power, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data2, aes(x = delta, y= Power, group = Threshold,color = Threshold, linetype = Threshold)) +
  facet_wrap(~Scenario, labeller = as_labeller(appender, default = label_parsed))+
  ylab(element_blank()) +
  xlab(element_blank()) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


Fig_FDR2 =  ggplot() +
  geom_point(data = plot_data2, aes(x = delta, y= FDR, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data2, aes(x = delta, y= FDR, group = Threshold,color = Threshold, linetype = Threshold)) +
  ylim(c(0,0.3)) +
  ylab(element_blank()) +
  xlab(expression(delta)) +
  theme_bw() +
  geom_hline(yintercept = q_fdr, linetype='dashed', alpha=0.5) +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


plot_data3 = data.frame(Power = output_table_power[,3], FDR = output_table_fdr[,3], `Threshold` = rep(c('SAS', 'DM', 'DSA', 'DSM'), length(parameter_proportion)), `delta` = rep(factor(parameter_proportion, level = as.character(parameter_proportion)), each=4))

colnames(plot_data3) = c('Power', 'FDR', 'Threshold', 'delta')
plot_data3$Scenario = 0.55
plot_data3$Threshold = factor(plot_data3$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))
Fig_power3 =  ggplot() +
  geom_point(data = plot_data3, aes(x = delta, y= Power, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data3, aes(x = delta, y= Power, group = Threshold,color = Threshold, linetype = Threshold)) +
  facet_wrap(~Scenario, labeller = as_labeller(appender, default = label_parsed))+
  xlab(element_blank()) +
  ylab(element_blank()) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


Fig_FDR3 =  ggplot() +
  geom_point(data = plot_data3, aes(x = delta, y= FDR, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data3, aes(x = delta, y= FDR, group = Threshold,color = Threshold, linetype = Threshold)) +
  ylim(c(0,0.3)) +
  xlab(expression(delta)) +
  ylab(element_blank()) +
  theme_bw() +
  geom_hline(yintercept = q_fdr, linetype='dashed', alpha=0.5) +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))

Fig1 = Fig_power1 + Fig_power2 + Fig_power3  + Fig_FDR1 + Fig_FDR2 +  Fig_FDR3 + plot_layout(ncol = 3, guides = 'collect')
ggsave('DS_5_1.jpg',Fig1, width = 9, height = 5.25, dpi = 400)
```

```{r}
Fig1
```

```{r, results = 'hide'}
output_table_fdr = data.frame(matrix(0,4*length(parameter_proportion),length(parameter_magnitude)))
output_table_power = data.frame(matrix(0,4*length(parameter_proportion),length(parameter_magnitude)))

DD_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
DD_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
S_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
S_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
SPlus_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
SPlus_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
Smin_fdr_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))
Smin_power_m = matrix(0,length(parameter_proportion),length(parameter_magnitude))

Output_fdr_power <- foreach (time = 1:Rep_times, .packages =c('MASS', 'glmnet')) %dopar%  {
  source('Functions.R')
  set.seed(time+seeds)
  print(Sys.time())
  X_matrix = mvrn(n, rep(0,d_X), Sigma)
  X_matrix = X_matrix[,sample(d_X)]
  n_index = sample(n,n/2)
  X_matrix1 = X_matrix[n_index,]
  X_matrix2 = X_matrix[setdiff(c(1:n), n_index),]
  M1 = get_M(X_matrix1)
  M2 = get_M(X_matrix2)
  e = rnorm(n,0,1)
  
  DD_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  DD_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  S_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  S_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  SPlus_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  SPlus_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  Smin_fdr_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  Smin_power_matrix = matrix(0,length(parameter_proportion),length(parameter_magnitude))
  
  for (ii in 1:length(parameter_proportion)) {
    for (jj in 1:length(parameter_magnitude)) {
      negative = parameter_proportion[ii]
      positive = 1 - negative
      posi_len = round(positive*d_h1)
      nega_len = d_h1 - posi_len
      magnitude = parameter_magnitude[jj]
      c1 = rep(magnitude,round(posi_len))
      c2 = rep(-0.25,round(nega_len))
      coef_X = matrix(c(rep(0,d_h0), c1, c2), d_X) 
      
      Y = X_matrix %*% coef_X + e
      Y1 = Y[n_index,]
      Y2 = Y[setdiff(c(1:n), n_index),]
      
      cvfit <- cv.glmnet(X_matrix, Y, intercept = F, standardize = F)
      lambda <- cvfit$lambda.min*1.2
      beta1 <- as.vector(glmnet(X_matrix1, Y1, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
      beta2 <- as.vector(glmnet(X_matrix2, Y2, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
      index_beta1 = which(beta1 == 0)
      index_beta2 = which(beta2 == 0)
      
      beta1_d = as.numeric(beta1 + 2/n*M1%*%t(X_matrix1)%*%(Y1 - X_matrix1 %*% beta1))
      beta2_d = as.numeric(beta2 + 2/n*M2%*%t(X_matrix2)%*%(Y2 - X_matrix2 %*% beta2))
      
      sigma1 = sqrt(diag(M1%*%(t(X_matrix1)%*%diag(diag((Y1-X_matrix1%*%beta1)%*%t(Y1-X_matrix1%*%beta1)))%*%X_matrix1/(n/2))%*%t(M1)))
      sigma2 = sqrt(diag(M2%*%(t(X_matrix2)%*%diag(diag((Y2-X_matrix2%*%beta2)%*%t(Y2-X_matrix2%*%beta2)))%*%X_matrix2/(n/2))%*%t(M2)))
      
      X1 = beta1_d/sigma1
      X2 = beta2_d/sigma2
      
      index1 = intersect(which(X1>0),which(X2>0))
      index2 = intersect(which(X1<0),which(X2>0))
      index3 = intersect(which(X1<0),which(X2<0))
      index4 = intersect(which(X1>0),which(X2<0))
      
      X1_4444 = c(X1[c(index2,index4)])
      X2_4444 = c(X2[c(index2,index4)])
      
      h0 = 1.0*c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
      h1 = 1.4*c(bandwidth.nrd(X1), bandwidth.nrd(X2))
      
      Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
      f0_hat0 = function(x){
        return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
      }
      f0_hat = function(x){
        return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
      }
      
      Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
      f_hat = function(x){
        return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
      }
      
      Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
      lfdr_points_2 = rep(1,2*length(index2))
      lfdr_points_4 = rep(1,2*length(index4))
      lfdr_points13 = lfdr_points13 = rep(1,length(c(index1,index3)))
      lfdr_points13 = apply(cbind(X1[c(index1,index3)],X2[c(index1,index3)]), 1, Lfdr_hat13)
      lfdr_points_2= apply(cbind(c(X1[index2],-X1[index2]),c(-X2[index2], X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
      lfdr_points_4= apply(cbind(c(-X1[index4],X1[index4]),c(X2[index4], -X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
      
      get_localfdr_threshold_half <- function(lfdr13, lfdr2, lfdr4,q_fdr){
        t = sort(c(lfdr13,lfdr2,lfdr4))
        t[t==1]=0.9999
        Ta = sapply(t,function(x){(0.5*(length(lfdr4[lfdr4<=x]) + length(lfdr2[lfdr2<=x])))/max(1,length(lfdr13[lfdr13<=x]))})
        sh = max(t[which(Ta<q_fdr)]) 
        
        return(sh)
      }
      
      fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, q_fdr)
      label_X1X2_13 = label_X1X2[c(index1,index3)]
      number_d = length(which(lfdr_points13<fdr_q))
      number_td = length(intersect(which(lfdr_points13<fdr_q), which(label_X1X2_13 != 'Null')))
      
      get_conventional_threshold <- function(S, q_fdr){
        t = sort(abs(S))
        Ta = sapply(t,function(x){(length(S[S<(-x)]))/max(1,length(S[S>x]))})
        sh = min(t[which(Ta<q_fdr)])
        return(sh)
      }
      
      S_tol = X1*X2
      sh = get_conventional_threshold(S_tol,q_fdr)
      S_fdr = length(intersect(which(S_tol > sh), which(label_X1X2 == 'Null'))) / max(length(which(S_tol > sh)),1)
      S_power = length(intersect(which(S_tol > sh), which(label_X1X2 != 'Null'))) / (d_X - d_h0)
      
      SPlus_tol = sign(X1*X2)*(abs(X1) + abs(X2))
      sh = get_conventional_threshold(SPlus_tol,q_fdr)
      SPlus_fdr = length(intersect(which(SPlus_tol > sh), which(label_X1X2 == 'Null'))) / max(length(which(SPlus_tol > sh)),1)
      SPlus_power = length(intersect(which(SPlus_tol > sh), which(label_X1X2 != 'Null'))) / (d_X - d_h0)
      
      Smin_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
      sh = get_conventional_threshold(Smin_tol,q_fdr)
      Smin_fdr = length(intersect(which(Smin_tol > sh), which(label_X1X2 == 'Null'))) / max(length(which(Smin_tol > sh)),1)
      Smin_power = length(intersect(which(Smin_tol > sh), which(label_X1X2 != 'Null'))) / (d_X - d_h0)      
      
      DD_fdr = (number_d - number_td)/ max(1,number_d)
      DD_power = (number_td)/(d_X-d_h0)
      
      
      DD_fdr_matrix[ii,jj] = DD_fdr
      DD_power_matrix[ii,jj] = DD_power
      S_fdr_matrix[ii,jj] = S_fdr
      S_power_matrix[ii,jj] = S_power
      SPlus_fdr_matrix[ii,jj] = SPlus_fdr
      SPlus_power_matrix[ii,jj] = SPlus_power
      Smin_fdr_matrix[ii,jj] = Smin_fdr
      Smin_power_matrix[ii,jj] = Smin_power
    }
  }
  
  return(list(DD_fdr_matrix, DD_power_matrix, S_fdr_matrix, S_power_matrix, SPlus_fdr_matrix, SPlus_power_matrix, Smin_fdr_matrix, Smin_power_matrix))
}

for (i in 1:Rep_times) {
  DD_fdr_m  = DD_fdr_m + Output_fdr_power[[i]][[1]]/Rep_times
  DD_power_m  = DD_power_m + Output_fdr_power[[i]][[2]]/Rep_times
  S_fdr_m  = S_fdr_m + Output_fdr_power[[i]][[3]]/Rep_times
  S_power_m  = S_power_m + Output_fdr_power[[i]][[4]]/Rep_times
  SPlus_fdr_m  = SPlus_fdr_m + Output_fdr_power[[i]][[5]]/Rep_times
  SPlus_power_m  = SPlus_power_m + Output_fdr_power[[i]][[6]]/Rep_times
  Smin_fdr_m  = Smin_fdr_m + Output_fdr_power[[i]][[7]]/Rep_times
  Smin_power_m  = Smin_power_m + Output_fdr_power[[i]][[8]]/Rep_times
}

for (i in 1:length(parameter_magnitude)) {
  output_table_fdr[,i] = as.vector(t(cbind(DD_fdr_m[,i],S_fdr_m[,i],SPlus_fdr_m[,i],Smin_fdr_m[,i])))
  output_table_power[,i] = as.vector(t(cbind(DD_power_m[,i],S_power_m[,i],SPlus_power_m[,i],Smin_power_m[,i])))
}


appender <- function(string){TeX(paste("\\mu = $", string))}
plot_data1 = data.frame(Power = output_table_power[,1], FDR = output_table_fdr[,1], `Threshold` = rep(c('SAS', 'DM', 'DSA', 'DSM'), length(parameter_proportion)), `delta` = rep(factor(parameter_proportion, level = as.character(parameter_proportion)), each=4))
plot_data1$Threshold = factor(plot_data1$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))
colnames(plot_data1) = c('Power', 'FDR', 'Threshold', 'delta')
plot_data1$Scenario = 0.25
plot_data1$Threshold = factor(plot_data1$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))

Fig_power1 =  ggplot() +
  geom_point(data = plot_data1, aes(x = delta, y= Power, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data1, aes(x = delta, y= Power, group = Threshold,color = Threshold, linetype = Threshold)) +
  facet_wrap(~Scenario, labeller = as_labeller(appender, default = label_parsed))+
  xlab(element_blank()) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


Fig_FDR1 =  ggplot() +
  geom_point(data = plot_data1, aes(x = delta, y= FDR, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data1, aes(x = delta, y= FDR, group = Threshold,color = Threshold, linetype = Threshold)) +
  ylim(c(0,0.3)) +
  xlab(expression(delta)) +
  theme_bw() +
  geom_hline(yintercept = q_fdr, linetype='dashed', alpha=0.5) +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


plot_data2 = data.frame(Power = output_table_power[,2], FDR = output_table_fdr[,2], `Threshold` = rep(c('SAS', 'DM', 'DSA', 'DSM'), length(parameter_proportion)), `delta` = rep(factor(parameter_proportion, level = as.character(parameter_proportion)), each=4))
colnames(plot_data2) = c('Power', 'FDR', 'Threshold', 'delta')
plot_data2$Scenario = 0.4
plot_data2$Threshold = factor(plot_data2$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))
Fig_power2 =  ggplot() +
  geom_point(data = plot_data2, aes(x = delta, y= Power, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data2, aes(x = delta, y= Power, group = Threshold,color = Threshold, linetype = Threshold)) +
  facet_wrap(~Scenario, labeller = as_labeller(appender, default = label_parsed))+
  ylab(element_blank()) +
  xlab(element_blank()) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))

Fig_FDR2 =  ggplot() +
  geom_point(data = plot_data2, aes(x = delta, y= FDR, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data2, aes(x = delta, y= FDR, group = Threshold,color = Threshold, linetype = Threshold)) +
  ylim(c(0,0.3)) +
  ylab(element_blank()) +
  xlab(expression(delta)) +
  theme_bw() +
  geom_hline(yintercept = q_fdr, linetype='dashed', alpha=0.5) +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


plot_data3 = data.frame(Power = output_table_power[,3], FDR = output_table_fdr[,3], `Threshold` = rep(c('SAS', 'DM', 'DSA', 'DSM'), length(parameter_proportion)), `delta` = rep(factor(parameter_proportion, level = as.character(parameter_proportion)), each=4))

colnames(plot_data3) = c('Power', 'FDR', 'Threshold', 'delta')
plot_data3$Scenario = 0.55
plot_data3$Threshold = factor(plot_data3$Threshold, levels = c('SAS','DM','DSA','DSM'),labels = c('SAS','DM','DSA','DSM'))
Fig_power3 =  ggplot() +
  geom_point(data = plot_data3, aes(x = delta, y= Power, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data3, aes(x = delta, y= Power, group = Threshold,color = Threshold, linetype = Threshold)) +
  facet_wrap(~Scenario, labeller = as_labeller(appender, default = label_parsed))+
  xlab(element_blank()) +
  ylab(element_blank()) +
  theme_bw() +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))


Fig_FDR3 =  ggplot() +
  geom_point(data = plot_data3, aes(x = delta, y= FDR, color = Threshold, shape = Threshold), alpha =0.85) +
  geom_line(data = plot_data3, aes(x = delta, y= FDR, group = Threshold,color = Threshold, linetype = Threshold)) +
  ylim(c(0,0.3)) +
  xlab(expression(delta)) +
  ylab(element_blank()) +
  theme_bw() +
  geom_hline(yintercept = q_fdr, linetype='dashed', alpha=0.5) +
  theme(legend.title=element_blank(),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background= element_rect(colour = "transparent", fill = "transparent"))

Fig1 = Fig_power1 + Fig_power2 + Fig_power3  + Fig_FDR1 + Fig_FDR2 +  Fig_FDR3 + plot_layout(ncol = 3, guides = 'collect')
ggsave('DS_5.jpg',Fig1, width = 9, height = 5.25, dpi = 400)

stopImplicitCluster()
stopCluster(cl)
```

```{r}
Fig1
```