---
title: "HIV Data Analysis (Bar Plot)"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, results = 'hide'}
path = dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(path)
library(MASS) 
library(ggplot2)
library(glmnet)
library(knockoff)
library(doSNOW)
library(foreach)
library(doParallel)
source('Functions.R')
cl <- makeCluster(10, outfile = 'Realdata_outs.out')
registerDoParallel(cl)
registerDoSNOW(cl)
clusterEvalQ(cl = cl, RhpcBLASctl::blas_set_num_threads(1))

Rep_times = 50
fdr_target = 0.1
drug_class = 'PI' # Possible drug types are 'PI', 'NRTI', and 'NNRTI'. In the paper we restrict to PI and NRTI.

### Cleaning and Fetching the data
base_url = 'https://hivdb.stanford.edu/_wrapper/pages/published_analysis/genophenoPNAS2006'
gene_url = paste(base_url, 'DATA', paste0(drug_class, '_DATA.txt'), sep='/')
tsm_url = paste(base_url, 'MUTATIONLISTS', 'NP_TSM', drug_class, sep='/')
gene_df = read.delim(gene_url, na.string = c('NA', ''), stringsAsFactors = FALSE)
tsm_df = read.delim(tsm_url, header = FALSE, stringsAsFactors = FALSE)
names(tsm_df) = c('Position', 'Mutations')

### Removing the rows with error flags or nonstandard mutation codes
pos_start = which(names(gene_df) == 'P1')
pos_cols = seq.int(pos_start, ncol(gene_df))
valid_rows = grepl_rows('^(\\.|-|[A-Zid]+)$', gene_df[,pos_cols])
gene_df = gene_df[valid_rows,]

### Prepare the design matrix and response variable.
# Flatten a matrix to a vector with names from concatenating row/column names
# Construct preliminary design matrix.
muts = c(LETTERS, 'i', 'd')
X = outer(muts, as.matrix(gene_df[,pos_cols]), Vectorize(grepl))
X = aperm(X, c(2,3,1))
dimnames(X)[[3]] <- muts
X = t(apply(X, 1, flatten_matrix))
mode(X) <- 'numeric'

# Remove any mutation/position pairs that never appear in the data.
X = X[,colSums(X) != 0]
X_ = X

# Extract response matrix.
Y11 = gene_df[,4:(pos_start-1)]
Y = gene_df[,4:(pos_start-1)]

output_table_dis = data.frame(matrix(ncol = 8, nrow = 0))

for (yy in 1:length(Y11)) {
  # Experiment
  y = log(Y11[,yy])
  missing = is.na(y)
  y = y[!missing]

  AdpK_td_list  = list(); AdpK_fd_list  = list()
  Kminus_td_list  = list(); Kminus_fd_list  = list()
  Ksquare_td_list  = list(); Ksquare_fd_list  = list()
  Kmax_td_list  = list(); Kmax_fd_list  = list()
  
  Output_dis <- foreach (time = 1:Rep_times, .packages =c('MASS', 'knockoff', 'glmnet')) %dopar%  {
    source('Functions.R')
    set.seed(time+88)
    print(paste("Rep time:", time))
    X = X_[!missing,]
    X = X[,colSums(X) >= 3]
    X = X[,colSums(abs(cor(X)-1) < 1e-4) == 1]
    X_matrix = X
    index = c()
    ii = 0
    for (i in colnames(X_matrix)) {
      ii = ii + 1
      if(get_position(i) %in% tsm_df$Position){
        index = c(index, ii)
      }
    }
    n=length(y)
    Y = as.matrix(y)
    X_knockoffs = create.second_order(X_matrix,  method='equi')
    X_matrix = cbind(X_matrix, X_knockoffs)
    cvfit <- cv.glmnet(X_matrix, Y, intercept = F, standardize = F)
    lambda <- cvfit$lambda.min
    beta1 <- as.vector(glmnet(X_matrix, Y, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
    index_beta1 = which(beta1 == 0)
    ## Get the debiased Lasso estimator
    M1 = get_M(X_matrix)
    beta1_d = as.numeric(beta1 + 1/n*M1%*%t(X_matrix)%*%(Y - X_matrix %*% beta1))
    ## Get the variance for the debiased Lasso estimator (up to a scaling factor)
    sigma1 = sqrt(diag(M1%*%(t(X_matrix)%*%diag(diag((Y-X_matrix%*%beta1)%*%t(Y-X_matrix%*%beta1)))%*%X_matrix/(n/1))%*%t(M1)))
    tmp = beta1_d/sigma1
    d_X = ncol(X_matrix)/2
    X1 = tmp[1:(d_X)] - tmp[(d_X+1):(d_X*2)]
    X2 = tmp[1:(d_X)] + tmp[(d_X+1):(d_X*2)]
  
    index1 = intersect(which(X1>0),which(X2>0))
    index2 = intersect(which(X1<0),which(X2>0))
    index3 = intersect(which(X1<0),which(X2<0))
    index4 = intersect(which(X1>0),which(X2<0))
    
    X1_4444 = c(X1[c(index2,index4)])
    X2_4444 = c(X2[c(index2,index4)])
    
    h0 = c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
    h1 = c(bandwidth.nrd(X1), bandwidth.nrd(X2)) 
    
    Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
    f0_hat0 = function(x){
      return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
    }
    f0_hat = function(x){
      return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
    }
    
    Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
    f_hat = function(x){
      return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
    }
    
    Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
    lfdr_points_2 = rep(1,2*length(index2))
    lfdr_points_4 = rep(1,2*length(index4))
    lfdr_points13 = lfdr_points13 = rep(1,length(c(index1,index3)))
    lfdr_points13 = apply(cbind(X1[c(index1,index3)],X2[c(index1,index3)]), 1, Lfdr_hat13)
    lfdr_points_2= apply(cbind(c(X1[index2],-X1[index2]),c(-X2[index2], X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    lfdr_points_4= apply(cbind(c(-X1[index4],X1[index4]),c(X2[index4], -X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    
    get_conventional_threshold <- function(S, q_loc_fdr){
      t = sort(abs(S))
      Ta = sapply(t,function(x){(1+length(S[S<(-x)]))/max(1,length(S[S>x]))})
      sh = min(t[which(Ta<=q_loc_fdr)])
      return(sh)
    }
    
    get_localfdr_threshold_half <- function(lfdr13, lfdr2, lfdr4,q_loc_fdr){
      t = sort(c(lfdr13,lfdr2,lfdr4))
      t[t==1]=0.9999
      Ta = sapply(t,function(x){(1+0.5*(length(lfdr4[lfdr4<=x])+ length(lfdr2[lfdr2<=x])))/max(1,length(lfdr13[lfdr13<=x]))})
      sh = max(t[which(Ta<=q_loc_fdr)]) 
      return(sh)
    }

    fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, fdr_target)
    lfdr_points_t = rep(1,length(X1))
    lfdr_points_t[c(index1,index3)] = lfdr_points13
    selected = which(lfdr_points_t<=fdr_q)
    
    selected_AdpK = colnames(X)[selected]
    AdpK = dr(selected_AdpK)
    
    Sminus_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
    sh = get_conventional_threshold(Sminus_tol,fdr_target)
    selected_Kminus = colnames(X)[which(Sminus_tol > sh)]
    Kminus = dr(selected_Kminus)
    
    SSquare_tol = X1*X2
    sh = get_conventional_threshold(SSquare_tol,fdr_target)
    selected_Ksquare = colnames(X)[which(SSquare_tol > sh)]
    Ksquare = dr(selected_Ksquare)
    
    Smax_tol = sign(X1*X2)*(abs(X1) + abs(X2))
    sh = get_conventional_threshold(Smax_tol,fdr_target)
    selected_Kmax = colnames(X)[which(Smax_tol > sh)]
    Kmax = dr(selected_Kmax)

    return(list(AdpK[[1]], AdpK[[2]], Kminus[[1]], Kminus[[2]], Ksquare[[1]], Ksquare[[2]], Kmax[[1]], Kmax[[2]]))
  }
  
  for (i in 1:Rep_times) {
    AdpK_td_list[i]  = Output_dis[[i]][[1]]
    AdpK_fd_list[i]  = Output_dis[[i]][[2]]
    Kminus_td_list[i]  = Output_dis[[i]][[3]]
    Kminus_fd_list[i]  = Output_dis[[i]][[4]]
    Ksquare_td_list[i]  = Output_dis[[i]][[5]]
    Ksquare_fd_list[i]  = Output_dis[[i]][[6]]
    Kmax_td_list[i]  = Output_dis[[i]][[7]]
    Kmax_fd_list[i]  = Output_dis[[i]][[8]]
  }
  AdpK_td_list  = unlist(AdpK_td_list); AdpK_fd_list  = unlist(AdpK_fd_list)
  Kminus_td_list  = unlist(Kminus_td_list); Kminus_fd_list  = unlist(Kminus_fd_list)
  Ksquare_td_list  = unlist(Ksquare_td_list); Ksquare_fd_list  = unlist(Ksquare_fd_list)
  Kmax_td_list  = unlist(Kmax_td_list); Kmax_fd_list  = unlist(Kmax_fd_list)
  
  output = data.frame(AdpK_td_list, AdpK_fd_list,
                      Kminus_td_list, Kminus_fd_list,
                      Ksquare_td_list, Ksquare_fd_list,
                      Kmax_td_list, Kmax_fd_list)
  mean_dis = apply(output, 2, mean)
  output_table_dis = rbind(output_table_dis, mean_dis)
}
rownames(output_table_dis)  = colnames(Y)
colnames(output_table_dis) = c('AdpK_TD', 'AdpK_FD','KLCD_TD','KLCD_FD', 
                               'KSCD_TD', 'KSCD_FD', 'KLSM_TD', 'KLSM_FD')


Discovery = factor(rep(c('In TSM list', 'Not in TSM list'), times = length(output_table_dis)/2*length(Y)),
                   levels = c('Not in TSM list', 'In TSM list'))
Methods = factor(rep(c('SAS', 'SAS','KLCD','KLCD', 
                       'KSCD', 'KSCD', 'KLSM', 'KLSM'), times = length(Y)),
                 levels = c('SAS','KLCD', 'KSCD', 'KLSM'))
Values = as.vector(t(as.matrix(output_table_dis)))
Drug = rep(paste('Resistance to',colnames(Y)), each = ncol(output_table_dis))
plot_data = data.frame(Discovery, Methods, Values, Drug)
plot_data = plot_data[plot_data$Methods %in% c('SAS','KLCD', 'KSCD', 'KLSM'),]
data_text<-data.frame(label=c("n=767  p=201","n=328  p=147","n=825  p=206","n=515  p=184",
                              "n=842  p=207","n=793  p=205","n=824  p=206"),
                      Drug=paste('Resistance to',colnames(Y)),
                      x=rep(2.5, 7),
                      y=rep(37, 7))

Fig1 = ggplot(plot_data, aes(x=Methods, y=Values, fill=Discovery)) + 
  geom_bar(stat="identity",position = "stack", alpha = 0.95, color = 'white') + 
  geom_text(aes(label=round(Values,2)),position = position_stack(vjust = 0.5),size=2) +
  ylab('Numbers of the discovered mutations') + 
  xlab('') + 
  ylim(c(0,38.5))+
  scale_fill_manual(values = c("In TSM list"="#a3cd5b",
                               "Not in TSM list"="#8ea0cc")) +
  theme_bw() + 
  facet_wrap(~Drug, ncol=4, scales = "free_x") +
  geom_text(data=data_text,mapping=aes(x=x,y=y,label=label,fill=NULL),size=3)+
  theme(axis.text.x = element_text(angle=60, hjust = 1),
        legend.position = c(0.88,0.2),
        legend.title = element_blank())
ggsave('Figures/HIV1_q01_1.jpg',Fig1, width = 6, height = 5, dpi = 600)
```

```{r}
Fig1
```


```{r, results = 'hide'}
output_table_dis = data.frame(matrix(ncol = 8, nrow = 0))

for (yy in 1:length(Y11)) {
  # Experiment
  y = log(Y11[,yy])
  missing = is.na(y)
  y = y[!missing]
  
  AdpK_td_list  = list(); AdpK_fd_list  = list()
  Kminus_td_list  = list(); Kminus_fd_list  = list()
  Ksquare_td_list  = list(); Ksquare_fd_list  = list()
  Kmax_td_list  = list(); Kmax_fd_list  = list()
  
  Output_dis <- foreach (time = 1:Rep_times, .packages =c('MASS', 'knockoff', 'glmnet')) %dopar%  {
    source('Functions.R')
    set.seed(time+88)
    # print(paste("Rep time:", time))
    X = X_[!missing,]
    X = X[,colSums(X) >= 3]
    X = X[,colSums(abs(cor(X)-1) < 1e-4) == 1]
    X_matrix = X
    index = c()
    ii = 0
    for (i in colnames(X_matrix)) {
      ii = ii + 1
      if(get_position(i) %in% tsm_df$Position){
        index = c(index, ii)
      }
    }
    n=length(y)
    Y = as.matrix(y)
    X_knockoffs = create.second_order(X_matrix,  method='equi')
    X_matrix = cbind(X_matrix, X_knockoffs)
    cvfit <- cv.glmnet(X_matrix, Y, intercept = F, standardize = F)
    lambda <- cvfit$lambda.min
    beta1 <- as.vector(glmnet(X_matrix, Y, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
    index_beta1 = which(beta1 == 0)
    ## Get the debiased Lasso estimator
    M1 = get_M(X_matrix)
    beta1_d = as.numeric(beta1 + 1/n*M1%*%t(X_matrix)%*%(Y - X_matrix %*% beta1))
    ## Get the variance for the debiased Lasso estimator (up to a scaling factor)
    sigma1 = sqrt(diag(M1%*%(t(X_matrix)%*%diag(diag((Y-X_matrix%*%beta1)%*%t(Y-X_matrix%*%beta1)))%*%X_matrix/(n/1))%*%t(M1)))
    tmp = beta1_d/sigma1
    d_X = ncol(X_matrix)/2
    X1 = tmp[1:(d_X)] - tmp[(d_X+1):(d_X*2)]
    X2 = tmp[1:(d_X)] + tmp[(d_X+1):(d_X*2)]
    
    index1 = intersect(which(X1>0),which(X2>0))
    index2 = intersect(which(X1<0),which(X2>0))
    index3 = intersect(which(X1<0),which(X2<0))
    index4 = intersect(which(X1>0),which(X2<0))
    
    X1_4444 = c(X1[c(index2,index4)])
    X2_4444 = c(X2[c(index2,index4)])
    
    h0 = c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
    h1 = c(bandwidth.nrd(X1), bandwidth.nrd(X2)) 
    
    Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
    f0_hat0 = function(x){
      return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
    }
    f0_hat = function(x){
      return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
    }
    
    Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
    f_hat = function(x){
      return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
    }
    
    Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
    lfdr_points_2 = rep(1,2*length(index2))
    lfdr_points_4 = rep(1,2*length(index4))
    lfdr_points13 = lfdr_points13 = rep(1,length(c(index1,index3)))
    lfdr_points13 = apply(cbind(X1[c(index1,index3)],X2[c(index1,index3)]), 1, Lfdr_hat13)
    lfdr_points_2= apply(cbind(c(X1[index2],-X1[index2]),c(-X2[index2], X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    lfdr_points_4= apply(cbind(c(-X1[index4],X1[index4]),c(X2[index4], -X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    
    get_conventional_threshold <- function(S, q_loc_fdr){
      t = sort(abs(S))
      Ta = sapply(t,function(x){(length(S[S<(-x)]))/max(1,length(S[S>x]))})
      sh = min(t[which(Ta<=q_loc_fdr)])
      return(sh)
    }
    
    get_localfdr_threshold_half <- function(lfdr13, lfdr2, lfdr4,q_loc_fdr){
      t = sort(c(lfdr13,lfdr2,lfdr4))
      t[t==1]=0.9999
      Ta = sapply(t,function(x){(0.5*(length(lfdr4[lfdr4<=x])+ length(lfdr2[lfdr2<=x])))/max(1,length(lfdr13[lfdr13<=x]))})
      sh = max(t[which(Ta<=q_loc_fdr)]) 
      return(sh)
    }
    
    fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, fdr_target)
    lfdr_points_t = rep(1,length(X1))
    lfdr_points_t[c(index1,index3)] = lfdr_points13
    selected = which(lfdr_points_t<=fdr_q)
    
    selected_AdpK = colnames(X)[selected]
    AdpK = dr(selected_AdpK)
    
    Sminus_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
    sh = get_conventional_threshold(Sminus_tol,fdr_target)
    selected_Kminus = colnames(X)[which(Sminus_tol > sh)]
    Kminus = dr(selected_Kminus)
    
    SSquare_tol = X1*X2
    sh = get_conventional_threshold(SSquare_tol,fdr_target)
    selected_Ksquare = colnames(X)[which(SSquare_tol > sh)]
    Ksquare = dr(selected_Ksquare)
    
    Smax_tol = sign(X1*X2)*(abs(X1) + abs(X2))
    sh = get_conventional_threshold(Smax_tol,fdr_target)
    selected_Kmax = colnames(X)[which(Smax_tol > sh)]
    Kmax = dr(selected_Kmax)
    
    return(list(AdpK[[1]], AdpK[[2]], Kminus[[1]], Kminus[[2]], Ksquare[[1]], Ksquare[[2]], Kmax[[1]], Kmax[[2]]))
  }
  
  for (i in 1:Rep_times) {
    AdpK_td_list[i]  = Output_dis[[i]][[1]]
    AdpK_fd_list[i]  = Output_dis[[i]][[2]]
    Kminus_td_list[i]  = Output_dis[[i]][[3]]
    Kminus_fd_list[i]  = Output_dis[[i]][[4]]
    Ksquare_td_list[i]  = Output_dis[[i]][[5]]
    Ksquare_fd_list[i]  = Output_dis[[i]][[6]]
    Kmax_td_list[i]  = Output_dis[[i]][[7]]
    Kmax_fd_list[i]  = Output_dis[[i]][[8]]
  }
  AdpK_td_list  = unlist(AdpK_td_list); AdpK_fd_list  = unlist(AdpK_fd_list)
  Kminus_td_list  = unlist(Kminus_td_list); Kminus_fd_list  = unlist(Kminus_fd_list)
  Ksquare_td_list  = unlist(Ksquare_td_list); Ksquare_fd_list  = unlist(Ksquare_fd_list)
  Kmax_td_list  = unlist(Kmax_td_list); Kmax_fd_list  = unlist(Kmax_fd_list)
  
  output = data.frame(AdpK_td_list, AdpK_fd_list,
                      Kminus_td_list, Kminus_fd_list,
                      Ksquare_td_list, Ksquare_fd_list,
                      Kmax_td_list, Kmax_fd_list)
  mean_dis = apply(output, 2, mean)
  output_table_dis = rbind(output_table_dis, mean_dis)
}
rownames(output_table_dis)  = colnames(Y)
colnames(output_table_dis) = c('AdpK_TD', 'AdpK_FD','KLCD_TD','KLCD_FD', 
                               'KSCD_TD', 'KSCD_FD', 'KLSM_TD', 'KLSM_FD')


Discovery = factor(rep(c('In TSM list', 'Not in TSM list'), times = length(output_table_dis)/2*length(Y)),
                   levels = c('Not in TSM list', 'In TSM list'))
Methods = factor(rep(c('SAS', 'SAS','KLCD','KLCD', 
                       'KSCD', 'KSCD', 'KLSM', 'KLSM'), times = length(Y)),
                 levels = c('SAS','KLCD', 'KSCD', 'KLSM'))
Values = as.vector(t(as.matrix(output_table_dis)))
Drug = rep(paste('Resistance to',colnames(Y)), each = ncol(output_table_dis))
plot_data = data.frame(Discovery, Methods, Values, Drug)
plot_data = plot_data[plot_data$Methods %in% c('SAS','KLCD', 'KSCD', 'KLSM'),]
data_text<-data.frame(label=c("n=767  p=201","n=328  p=147","n=825  p=206","n=515  p=184",
                              "n=842  p=207","n=793  p=205","n=824  p=206"),
                      Drug=paste('Resistance to',colnames(Y)),
                      x=rep(2.5, 7),
                      y=rep(37, 7))

Fig1 = ggplot(plot_data, aes(x=Methods, y=Values, fill=Discovery)) + 
  geom_bar(stat="identity",position = "stack", alpha = 0.95, color = 'white') + 
  geom_text(aes(label=round(Values,2)),position = position_stack(vjust = 0.5),size=2) +
  ylab('Numbers of the discovered mutations') + 
  xlab('') + 
  ylim(c(0,38.5))+
  scale_fill_manual(values = c("In TSM list"="#a3cd5b",
                               "Not in TSM list"="#8ea0cc")) +
  theme_bw() + 
  facet_wrap(~Drug, ncol=4, scales = "free_x") +
  geom_text(data=data_text,mapping=aes(x=x,y=y,label=label,fill=NULL),size=3)+
  theme(axis.text.x = element_text(angle=60, hjust = 1),
        legend.position = c(0.88,0.2),
        legend.title = element_blank())
ggsave('Figures/HIV_q01.jpg',Fig1, width = 6, height = 5, dpi = 600)
```

```{r}
Fig1
```

```{r, results = 'hide'}
fdr_target = 0.2
output_table_dis = data.frame(matrix(ncol = 8, nrow = 0))

for (yy in 1:length(Y11)) {
  # Experiment
  y = log(Y11[,yy])
  missing = is.na(y)
  y = y[!missing]
  
  AdpK_td_list  = list(); AdpK_fd_list  = list()
  Kminus_td_list  = list(); Kminus_fd_list  = list()
  Ksquare_td_list  = list(); Ksquare_fd_list  = list()
  Kmax_td_list  = list(); Kmax_fd_list  = list()
  
  Output_dis <- foreach (time = 1:Rep_times, .packages =c('MASS', 'knockoff', 'glmnet')) %dopar%  {
    source('Functions.R')
    set.seed(time+88)
    # print(paste("Rep time:", time))
    X = X_[!missing,]
    X = X[,colSums(X) >= 3]
    X = X[,colSums(abs(cor(X)-1) < 1e-4) == 1]
    X_matrix = X
    index = c()
    ii = 0
    for (i in colnames(X_matrix)) {
      ii = ii + 1
      if(get_position(i) %in% tsm_df$Position){
        index = c(index, ii)
      }
    }
    n=length(y)
    Y = as.matrix(y)
    X_knockoffs = create.second_order(X_matrix,  method='equi')
    X_matrix = cbind(X_matrix, X_knockoffs)
    cvfit <- cv.glmnet(X_matrix, Y, intercept = F, standardize = F)
    lambda <- cvfit$lambda.min
    beta1 <- as.vector(glmnet(X_matrix, Y, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
    index_beta1 = which(beta1 == 0)
    ## Get the debiased Lasso estimator
    M1 = get_M(X_matrix)
    beta1_d = as.numeric(beta1 + 1/n*M1%*%t(X_matrix)%*%(Y - X_matrix %*% beta1))
    ## Get the variance for the debiased Lasso estimator (up to a scaling factor)
    sigma1 = sqrt(diag(M1%*%(t(X_matrix)%*%diag(diag((Y-X_matrix%*%beta1)%*%t(Y-X_matrix%*%beta1)))%*%X_matrix/(n/1))%*%t(M1)))
    tmp = beta1_d/sigma1
    d_X = ncol(X_matrix)/2
    X1 = tmp[1:(d_X)] - tmp[(d_X+1):(d_X*2)]
    X2 = tmp[1:(d_X)] + tmp[(d_X+1):(d_X*2)]
    
    index1 = intersect(which(X1>0),which(X2>0))
    index2 = intersect(which(X1<0),which(X2>0))
    index3 = intersect(which(X1<0),which(X2<0))
    index4 = intersect(which(X1>0),which(X2<0))
    
    X1_4444 = c(X1[c(index2,index4)])
    X2_4444 = c(X2[c(index2,index4)])
    
    h0 = c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
    h1 = c(bandwidth.nrd(X1), bandwidth.nrd(X2)) 
    
    Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
    f0_hat0 = function(x){
      return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
    }
    f0_hat = function(x){
      return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
    }
    
    Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
    f_hat = function(x){
      return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
    }
    
    Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
    lfdr_points_2 = rep(1,2*length(index2))
    lfdr_points_4 = rep(1,2*length(index4))
    lfdr_points13 = lfdr_points13 = rep(1,length(c(index1,index3)))
    lfdr_points13 = apply(cbind(X1[c(index1,index3)],X2[c(index1,index3)]), 1, Lfdr_hat13)
    lfdr_points_2= apply(cbind(c(X1[index2],-X1[index2]),c(-X2[index2], X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    lfdr_points_4= apply(cbind(c(-X1[index4],X1[index4]),c(X2[index4], -X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    
    get_conventional_threshold <- function(S, q_loc_fdr){
      t = sort(abs(S))
      Ta = sapply(t,function(x){(1+length(S[S<(-x)]))/max(1,length(S[S>x]))})
      sh = min(t[which(Ta<=q_loc_fdr)])
      return(sh)
    }
    
    get_localfdr_threshold_half <- function(lfdr13, lfdr2, lfdr4,q_loc_fdr){
      t = sort(c(lfdr13,lfdr2,lfdr4))
      t[t==1]=0.9999
      Ta = sapply(t,function(x){(1+0.5*(length(lfdr4[lfdr4<=x])+ length(lfdr2[lfdr2<=x])))/max(1,length(lfdr13[lfdr13<=x]))})
      sh = max(t[which(Ta<=q_loc_fdr)]) 
      return(sh)
    }
    
    fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, fdr_target)
    lfdr_points_t = rep(1,length(X1))
    lfdr_points_t[c(index1,index3)] = lfdr_points13
    selected = which(lfdr_points_t<=fdr_q)
    
    selected_AdpK = colnames(X)[selected]
    AdpK = dr(selected_AdpK)
    
    Sminus_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
    sh = get_conventional_threshold(Sminus_tol,fdr_target)
    selected_Kminus = colnames(X)[which(Sminus_tol > sh)]
    Kminus = dr(selected_Kminus)
    
    SSquare_tol = X1*X2
    sh = get_conventional_threshold(SSquare_tol,fdr_target)
    selected_Ksquare = colnames(X)[which(SSquare_tol > sh)]
    Ksquare = dr(selected_Ksquare)
    
    Smax_tol = sign(X1*X2)*(abs(X1) + abs(X2))
    sh = get_conventional_threshold(Smax_tol,fdr_target)
    selected_Kmax = colnames(X)[which(Smax_tol > sh)]
    Kmax = dr(selected_Kmax)
    
    return(list(AdpK[[1]], AdpK[[2]], Kminus[[1]], Kminus[[2]], Ksquare[[1]], Ksquare[[2]], Kmax[[1]], Kmax[[2]]))
  }
  
  for (i in 1:Rep_times) {
    AdpK_td_list[i]  = Output_dis[[i]][[1]]
    AdpK_fd_list[i]  = Output_dis[[i]][[2]]
    Kminus_td_list[i]  = Output_dis[[i]][[3]]
    Kminus_fd_list[i]  = Output_dis[[i]][[4]]
    Ksquare_td_list[i]  = Output_dis[[i]][[5]]
    Ksquare_fd_list[i]  = Output_dis[[i]][[6]]
    Kmax_td_list[i]  = Output_dis[[i]][[7]]
    Kmax_fd_list[i]  = Output_dis[[i]][[8]]
  }
  AdpK_td_list  = unlist(AdpK_td_list); AdpK_fd_list  = unlist(AdpK_fd_list)
  Kminus_td_list  = unlist(Kminus_td_list); Kminus_fd_list  = unlist(Kminus_fd_list)
  Ksquare_td_list  = unlist(Ksquare_td_list); Ksquare_fd_list  = unlist(Ksquare_fd_list)
  Kmax_td_list  = unlist(Kmax_td_list); Kmax_fd_list  = unlist(Kmax_fd_list)
  
  output = data.frame(AdpK_td_list, AdpK_fd_list,
                      Kminus_td_list, Kminus_fd_list,
                      Ksquare_td_list, Ksquare_fd_list,
                      Kmax_td_list, Kmax_fd_list)
  mean_dis = apply(output, 2, mean)
  output_table_dis = rbind(output_table_dis, mean_dis)
}
rownames(output_table_dis)  = colnames(Y)
colnames(output_table_dis) = c('AdpK_TD', 'AdpK_FD','KLCD_TD','KLCD_FD', 
                               'KSCD_TD', 'KSCD_FD', 'KLSM_TD', 'KLSM_FD')


Discovery = factor(rep(c('In TSM list', 'Not in TSM list'), times = length(output_table_dis)/2*length(Y)),
                   levels = c('Not in TSM list', 'In TSM list'))
Methods = factor(rep(c('SAS', 'SAS','KLCD','KLCD', 
                       'KSCD', 'KSCD', 'KLSM', 'KLSM'), times = length(Y)),
                 levels = c('SAS','KLCD', 'KSCD', 'KLSM'))
Values = as.vector(t(as.matrix(output_table_dis)))
Drug = rep(paste('Resistance to',colnames(Y)), each = ncol(output_table_dis))
plot_data = data.frame(Discovery, Methods, Values, Drug)
plot_data = plot_data[plot_data$Methods %in% c('SAS','KLCD', 'KSCD', 'KLSM'),]
data_text<-data.frame(label=c("n=767  p=201","n=328  p=147","n=825  p=206","n=515  p=184",
                              "n=842  p=207","n=793  p=205","n=824  p=206"),
                      Drug=paste('Resistance to',colnames(Y)),
                      x=rep(2.5, 7),
                      y=rep(37, 7))

Fig1 = ggplot(plot_data, aes(x=Methods, y=Values, fill=Discovery)) + 
  geom_bar(stat="identity",position = "stack", alpha = 0.95, color = 'white') + 
  geom_text(aes(label=round(Values,2)),position = position_stack(vjust = 0.5),size=2) +
  ylab('Numbers of the discovered mutations') + 
  xlab('') + 
  ylim(c(0,38.5))+
  scale_fill_manual(values = c("In TSM list"="#a3cd5b",
                               "Not in TSM list"="#8ea0cc")) +
  theme_bw() + 
  facet_wrap(~Drug, ncol=4, scales = "free_x") +
  geom_text(data=data_text,mapping=aes(x=x,y=y,label=label,fill=NULL),size=3)+
  theme(axis.text.x = element_text(angle=60, hjust = 1),
        legend.position = c(0.88,0.2),
        legend.title = element_blank())
ggsave('Figures/HIV1_q02_1.jpg',Fig1, width = 6, height = 5, dpi = 600)
```

```{r}
Fig1
```

```{r, results = 'hide'}
output_table_dis = data.frame(matrix(ncol = 8, nrow = 0))

for (yy in 1:length(Y11)) {
  # Experiment
  y = log(Y11[,yy])
  missing = is.na(y)
  y = y[!missing]
  
  AdpK_td_list  = list(); AdpK_fd_list  = list()
  Kminus_td_list  = list(); Kminus_fd_list  = list()
  Ksquare_td_list  = list(); Ksquare_fd_list  = list()
  Kmax_td_list  = list(); Kmax_fd_list  = list()
  
  Output_dis <- foreach (time = 1:Rep_times, .packages =c('MASS', 'knockoff', 'glmnet')) %dopar%  {
    source('Functions.R')
    set.seed(time+88)
    # print(paste("Rep time:", time))
    X = X_[!missing,]
    X = X[,colSums(X) >= 3]
    X = X[,colSums(abs(cor(X)-1) < 1e-4) == 1]
    X_matrix = X
    index = c()
    ii = 0
    for (i in colnames(X_matrix)) {
      ii = ii + 1
      if(get_position(i) %in% tsm_df$Position){
        index = c(index, ii)
      }
    }
    n=length(y)
    Y = as.matrix(y)
    X_knockoffs = create.second_order(X_matrix,  method='equi')
    X_matrix = cbind(X_matrix, X_knockoffs)
    cvfit <- cv.glmnet(X_matrix, Y, intercept = F, standardize = F)
    lambda <- cvfit$lambda.min
    beta1 <- as.vector(glmnet(X_matrix, Y, alpha = 1, lambda = lambda, intercept = F, standardize = F)$beta)
    index_beta1 = which(beta1 == 0)
    ## Get the debiased Lasso estimator
    M1 = get_M(X_matrix)
    beta1_d = as.numeric(beta1 + 1/n*M1%*%t(X_matrix)%*%(Y - X_matrix %*% beta1))
    ## Get the variance for the debiased Lasso estimator (up to a scaling factor)
    sigma1 = sqrt(diag(M1%*%(t(X_matrix)%*%diag(diag((Y-X_matrix%*%beta1)%*%t(Y-X_matrix%*%beta1)))%*%X_matrix/(n/1))%*%t(M1)))
    tmp = beta1_d/sigma1
    d_X = ncol(X_matrix)/2
    X1 = tmp[1:(d_X)] - tmp[(d_X+1):(d_X*2)]
    X2 = tmp[1:(d_X)] + tmp[(d_X+1):(d_X*2)]
    
    index1 = intersect(which(X1>0),which(X2>0))
    index2 = intersect(which(X1<0),which(X2>0))
    index3 = intersect(which(X1<0),which(X2<0))
    index4 = intersect(which(X1>0),which(X2<0))
    
    X1_4444 = c(X1[c(index2,index4)])
    X2_4444 = c(X2[c(index2,index4)])
    
    h0 = c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
    h1 = c(bandwidth.nrd(X1), bandwidth.nrd(X2)) 
    
    Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
    f0_hat0 = function(x){
      return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
    }
    f0_hat = function(x){
      return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
    }
    
    Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
    f_hat = function(x){
      return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
    }
    
    Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
    lfdr_points_2 = rep(1,2*length(index2))
    lfdr_points_4 = rep(1,2*length(index4))
    lfdr_points13 = lfdr_points13 = rep(1,length(c(index1,index3)))
    lfdr_points13 = apply(cbind(X1[c(index1,index3)],X2[c(index1,index3)]), 1, Lfdr_hat13)
    lfdr_points_2= apply(cbind(c(X1[index2],-X1[index2]),c(-X2[index2], X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    lfdr_points_4= apply(cbind(c(-X1[index4],X1[index4]),c(X2[index4], -X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
    
    get_conventional_threshold <- function(S, q_loc_fdr){
      t = sort(abs(S))
      Ta = sapply(t,function(x){(length(S[S<(-x)]))/max(1,length(S[S>x]))})
      sh = min(t[which(Ta<=q_loc_fdr)])
      return(sh)
    }
    
    get_localfdr_threshold_half <- function(lfdr13, lfdr2, lfdr4,q_loc_fdr){
      t = sort(c(lfdr13,lfdr2,lfdr4))
      t[t==1]=0.9999
      Ta = sapply(t,function(x){(0.5*(length(lfdr4[lfdr4<=x])+ length(lfdr2[lfdr2<=x])))/max(1,length(lfdr13[lfdr13<=x]))})
      sh = max(t[which(Ta<=q_loc_fdr)]) 
      return(sh)
    }
    
    fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, fdr_target)
    lfdr_points_t = rep(1,length(X1))
    lfdr_points_t[c(index1,index3)] = lfdr_points13
    selected = which(lfdr_points_t<=fdr_q)
    
    selected_AdpK = colnames(X)[selected]
    AdpK = dr(selected_AdpK)
    
    Sminus_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
    sh = get_conventional_threshold(Sminus_tol,fdr_target)
    selected_Kminus = colnames(X)[which(Sminus_tol > sh)]
    Kminus = dr(selected_Kminus)
    
    SSquare_tol = X1*X2
    sh = get_conventional_threshold(SSquare_tol,fdr_target)
    selected_Ksquare = colnames(X)[which(SSquare_tol > sh)]
    Ksquare = dr(selected_Ksquare)
    
    Smax_tol = sign(X1*X2)*(abs(X1) + abs(X2))
    sh = get_conventional_threshold(Smax_tol,fdr_target)
    selected_Kmax = colnames(X)[which(Smax_tol > sh)]
    Kmax = dr(selected_Kmax)
    
    return(list(AdpK[[1]], AdpK[[2]], Kminus[[1]], Kminus[[2]], Ksquare[[1]], Ksquare[[2]], Kmax[[1]], Kmax[[2]]))
  }
  
  for (i in 1:Rep_times) {
    AdpK_td_list[i]  = Output_dis[[i]][[1]]
    AdpK_fd_list[i]  = Output_dis[[i]][[2]]
    Kminus_td_list[i]  = Output_dis[[i]][[3]]
    Kminus_fd_list[i]  = Output_dis[[i]][[4]]
    Ksquare_td_list[i]  = Output_dis[[i]][[5]]
    Ksquare_fd_list[i]  = Output_dis[[i]][[6]]
    Kmax_td_list[i]  = Output_dis[[i]][[7]]
    Kmax_fd_list[i]  = Output_dis[[i]][[8]]
  }
  AdpK_td_list  = unlist(AdpK_td_list); AdpK_fd_list  = unlist(AdpK_fd_list)
  Kminus_td_list  = unlist(Kminus_td_list); Kminus_fd_list  = unlist(Kminus_fd_list)
  Ksquare_td_list  = unlist(Ksquare_td_list); Ksquare_fd_list  = unlist(Ksquare_fd_list)
  Kmax_td_list  = unlist(Kmax_td_list); Kmax_fd_list  = unlist(Kmax_fd_list)
  
  output = data.frame(AdpK_td_list, AdpK_fd_list,
                      Kminus_td_list, Kminus_fd_list,
                      Ksquare_td_list, Ksquare_fd_list,
                      Kmax_td_list, Kmax_fd_list)
  mean_dis = apply(output, 2, mean)
  output_table_dis = rbind(output_table_dis, mean_dis)
}
rownames(output_table_dis)  = colnames(Y)
colnames(output_table_dis) = c('AdpK_TD', 'AdpK_FD','KLCD_TD','KLCD_FD', 
                               'KSCD_TD', 'KSCD_FD', 'KLSM_TD', 'KLSM_FD')


Discovery = factor(rep(c('In TSM list', 'Not in TSM list'), times = length(output_table_dis)/2*length(Y)),
                   levels = c('Not in TSM list', 'In TSM list'))
Methods = factor(rep(c('SAS', 'SAS','KLCD','KLCD', 
                       'KSCD', 'KSCD', 'KLSM', 'KLSM'), times = length(Y)),
                 levels = c('SAS','KLCD', 'KSCD', 'KLSM'))
Values = as.vector(t(as.matrix(output_table_dis)))
Drug = rep(paste('Resistance to',colnames(Y)), each = ncol(output_table_dis))
plot_data = data.frame(Discovery, Methods, Values, Drug)
plot_data = plot_data[plot_data$Methods %in% c('SAS','KLCD', 'KSCD', 'KLSM'),]
data_text<-data.frame(label=c("n=767  p=201","n=328  p=147","n=825  p=206","n=515  p=184",
                              "n=842  p=207","n=793  p=205","n=824  p=206"),
                      Drug=paste('Resistance to',colnames(Y)),
                      x=rep(2.5, 7),
                      y=rep(37, 7))

Fig1 = ggplot(plot_data, aes(x=Methods, y=Values, fill=Discovery)) + 
  geom_bar(stat="identity",position = "stack", alpha = 0.95, color = 'white') + 
  geom_text(aes(label=round(Values,2)),position = position_stack(vjust = 0.5),size=2) +
  ylab('Numbers of the discovered mutations') + 
  xlab('') + 
  ylim(c(0,38.5))+
  scale_fill_manual(values = c("In TSM list"="#a3cd5b",
                               "Not in TSM list"="#8ea0cc")) +
  theme_bw() + 
  facet_wrap(~Drug, ncol=4, scales = "free_x") +
  geom_text(data=data_text,mapping=aes(x=x,y=y,label=label,fill=NULL),size=3)+
  theme(axis.text.x = element_text(angle=60, hjust = 1),
        legend.position = c(0.88,0.2),
        legend.title = element_blank())
ggsave('Figures/HIV_q02.jpg',Fig1, width = 6, height = 5, dpi = 600)
stopImplicitCluster()
stopCluster(cl)
```

```{r}
Fig1
```
