---
title: "HIV Data Analysis (Scatter Plot)"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, results = 'hide'}
rm(list = ls())
path = dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(path)
library(MASS) 
library(ggplot2)
library(glmnet)
library(knockoff)
library(doSNOW)
library(foreach)
library(doParallel)
cl <- makeCluster(13, outfile = 'outs.out')
registerDoParallel(cl)
registerDoSNOW(cl)
clusterEvalQ(cl = cl, RhpcBLASctl::blas_set_num_threads(1))
source('Functions.R')

drug_class = 'PI' # Possible drug types are 'PI', 'NRTI', and 'NNRTI'. In the paper we restrict to PI and NRTI.
### Cleaning and Fetching the data
base_url = 'https://hivdb.stanford.edu/_wrapper/pages/published_analysis/genophenoPNAS2006'
gene_url = paste(base_url, 'DATA', paste0(drug_class, '_DATA.txt'), sep='/')
tsm_url = paste(base_url, 'MUTATIONLISTS', 'NP_TSM', drug_class, sep='/')
gene_df = read.delim(gene_url, na.string = c('NA', ''), stringsAsFactors = FALSE)
tsm_df = read.delim(tsm_url, header = FALSE, stringsAsFactors = FALSE)
names(tsm_df) = c('Position', 'Mutations')

### Removing the rows with error flags or nonstandard mutation codes
pos_start = which(names(gene_df) == 'P1')
pos_cols = seq.int(pos_start, ncol(gene_df))
valid_rows = grepl_rows('^(\\.|-|[A-Zid]+)$', gene_df[,pos_cols])
gene_df = gene_df[valid_rows,]

### Prepare the design matrix and response variable.
# Flatten a matrix to a vector with names from concatenating row/column names
# Construct preliminary design matrix.
muts = c(LETTERS, 'i', 'd')
X = outer(muts, as.matrix(gene_df[,pos_cols]), Vectorize(grepl))
X = aperm(X, c(2,3,1))
dimnames(X)[[3]] <- muts
X = t(apply(X, 1, flatten_matrix))
mode(X) <- 'numeric'

# Remove any mutation/position pairs that never appear in the data.
X = X[,colSums(X) != 0]
X_ = X

# Extract response matrix.
Y11 = gene_df[,4:(pos_start-1)]
Y = gene_df[,4:(pos_start-1)]
proportion_table = data.frame(matrix(ncol = 4, nrow = 14))
output_table_dis = data.frame(matrix(ncol = 4, nrow = 0))
output_table_final = data.frame(matrix(0,ncol = 4, nrow = 7))
colnames(output_table_final) = c('Q1','Q2','Q3','Q4')

Rep_times = 50
Output_dis <- foreach (time = 1:Rep_times, .packages =c('MASS', 'knockoff', 'glmnet')) %dopar%  {
  source('Functions.R')
  set.seed(time+5000)
  print(paste("Rep time:", time))
  plot_lim = 0
  output_table_tmp = data.frame(matrix(ncol = 4, nrow = 7))
  for (yy in 1:length(Y11)) {
    y = log(Y11[,yy])
    missing = is.na(y)
    y = y[!missing]
    X = X_[!missing,]
    X = X[,colSums(X) >= 3]
    X = X[,colSums(abs(cor(X)-1) < 1e-4) == 1]
    index = c()
    ii = 0
    for (i in colnames(X)) {
      ii = ii + 1
      if(get_position(i) %in% tsm_df$Position){
        index = c(index, ii)
      }
    }
    n=length(y)
    n_index = sample(n,round(n/2))
    X_matrix = X
    Y = as.matrix(y)
    X_knockoffs = create.second_order(X_matrix,  method='equi')
    X_matrix = cbind(X_matrix, X_knockoffs)
    cvfit <- cv.glmnet(X_matrix, Y, intercept = F)
    lambda <- cvfit$lambda.min
    beta1 <- as.vector(glmnet(X_matrix, Y, alpha = 1, lambda = lambda, intercept = F)$beta)
    index_beta1 = which(beta1 == 0)
    M1 = get_M(X_matrix)
    ## Get the debiased Lasso estimator
    beta1_d = as.numeric(beta1 + 1/n*M1%*%t(X_matrix)%*%(Y - X_matrix %*% beta1))
    ## Get the variance for the debiased Lasso estimator (up to a scaling factor)
    sigma1 = sqrt(diag(M1%*%(t(X_matrix)%*%diag(diag((Y-X_matrix%*%beta1)%*%t(Y-X_matrix%*%beta1)))%*%X_matrix/(n/1))%*%t(M1)))
    tmp = beta1_d/sigma1
    d_X = ncol(X_matrix)/2
    X1 = tmp[1:(d_X)] - tmp[(d_X+1):(d_X*2)]
    X2 = tmp[1:(d_X)] + tmp[(d_X+1):(d_X*2)]
    tmp = ceiling(max(c(abs(X1), abs(X2)))*1000)/1000 + 0.05
    if(plot_lim <= tmp){
      plot_lim = tmp
    }
    l = length(X1)
    labels = rep('Not in TSM list', l)
    labels[index] = 'In TSM list'
    Index11 = which(X1>0 & X2>0)
    Index22 = which(X1<0 & X2>0)
    Index33 = which(X1<0 & X2<0)
    Index44 = which(X1>0 & X2<0)
    n_total = c(length(Index11),length(Index22),length(Index33),length(Index44))
    n_tsm = c(length(intersect(Index11,index)),length(intersect(Index22,index)),length(intersect(Index33,index)),length(intersect(Index44,index)))
    n_not_tsm = n_total-n_tsm
    
    proportion_table[2*yy-1,] = n_tsm
    proportion_table[2*yy,] = n_not_tsm
    tmp = cbind(X1, X2, rep(paste('Resistance to',colnames(Y11)[yy]), l), labels)
    output_table_dis = rbind(output_table_dis, tmp)
  }
  proportion_table1 = proportion_table[c(1,3,5,7,9,11,13),]
  for (i in 1:7) {
    output_table_tmp[i,] = proportion_table1[i,] / sum(proportion_table1[i,])
  }
  return(list(output_table_tmp))
}
for (i in 1:Rep_times) {
  output_table_final  = output_table_final + Output_dis[[i]][[1]]/Rep_times
}
stopImplicitCluster()
stopCluster(cl)
```

```{r}
output_table_final
```

```{r, results = 'hide'}
set.seed(5)
proportion_table = data.frame(matrix(ncol = 4, nrow = 14))
output_table_dis = data.frame(matrix(ncol = 4, nrow = 0))
plot_lim = 0
for (yy in 1:length(Y11)) {
  y = log(Y11[,yy])
  missing = is.na(y)
  y = y[!missing]
  X = X_[!missing,]
  X = X[,colSums(X) >= 3]
  X = X[,colSums(abs(cor(X)-1) < 1e-4) == 1]
  
  index = c()
  ii = 0
  for (i in colnames(X)) {
    ii = ii + 1
    if(get_position(i) %in% tsm_df$Position){
      index = c(index, ii)
    }
  }
  
  n=length(y)
  n_index = sample(n,round(n/2))
  X_matrix = X
  Y = as.matrix(y)
  X_knockoffs = create.second_order(X_matrix,  method='equi')
  X_matrix = cbind(X_matrix, X_knockoffs)
  cvfit <- cv.glmnet(X_matrix, Y, intercept = F)
  lambda <- cvfit$lambda.min
  beta1 <- as.vector(glmnet(X_matrix, Y, alpha = 1, lambda = lambda, intercept = F)$beta)
  index_beta1 = which(beta1 == 0)
  M1 = get_M(X_matrix)
  ## Get the debiased Lasso estimator
  beta1_d = as.numeric(beta1 + 1/n*M1%*%t(X_matrix)%*%(Y - X_matrix %*% beta1))
  ## Get the variance for the debiased Lasso estimator (up to a scaling factor)
  sigma1 = sqrt(diag(M1%*%(t(X_matrix)%*%diag(diag((Y-X_matrix%*%beta1)%*%t(Y-X_matrix%*%beta1)))%*%X_matrix/(n/1))%*%t(M1)))
  tmp = beta1_d/sigma1
  d_X = ncol(X_matrix)/2
  X1 = tmp[1:(d_X)] - tmp[(d_X+1):(d_X*2)]
  X2 = tmp[1:(d_X)] + tmp[(d_X+1):(d_X*2)]
  tmp = ceiling(max(c(abs(X1), abs(X2)))*1000)/1000 + 0.05
  if(plot_lim <= tmp){
    plot_lim = tmp
  }
  l = length(X1)
  labels = rep('Not in TSM list', l)
  labels[index] = 'In TSM list'
  Index11 = which(X1>0 & X2>0)
  Index22 = which(X1<0 & X2>0)
  Index33 = which(X1<0 & X2<0)
  Index44 = which(X1>0 & X2<0)
  n_total = c(length(Index11),length(Index22),length(Index33),length(Index44))
  n_tsm = c(length(intersect(Index11,index)),length(intersect(Index22,index)),length(intersect(Index33,index)),length(intersect(Index44,index)))
  n_not_tsm = n_total-n_tsm
  proportion_table[2*yy-1,] = n_tsm
  proportion_table[2*yy,] = n_not_tsm
  tmp = cbind(X1, X2, rep(paste('Resistance to',colnames(Y11)[yy]), l), labels)
  output_table_dis = rbind(output_table_dis, tmp)
}
colnames(output_table_dis) = c('T1','T2','Drug','Label')

output_table_dis$Drug = factor(output_table_dis$Drug)
output_table_dis$Label = output_table_dis$Label
output_table_dis$T1 = as.numeric(output_table_dis$T1)
output_table_dis$T2 = as.numeric(output_table_dis$T2)

Fig1 = ggplot(output_table_dis) + 
  geom_point(aes(T1,T2, fill=`Label`,shape = Label,alpha = Label, size =Label)) +
  theme_bw() +
  scale_alpha_discrete(range = c(0.8, 0.7)) + 
  scale_size_discrete(range = c(0.8, 1.1)) + 
  xlab(expression(italic(t^(1))))+
  ylab(expression(italic(t^(2))))+
  ylim(c(-plot_lim,plot_lim)) +
  xlim(c(-plot_lim-0.1,plot_lim+0.1)) + 
  scale_shape_manual(values = c(21,22),labels = c("In TSM list","Not in TSM list"))+
  scale_fill_manual(labels = c("In TSM list","Not in TSM list"),
                    values = c("In TSM list"="#a3cd5b","Not in TSM list"="#8ea0cc")) +
  facet_wrap(~Drug, ncol=4, scales = 'free_x') +
  theme(legend.title=element_blank(),
        plot.subtitle = element_text(family = "serif", size = 10, face = "bold", hjust = 0.5),
        legend.position = c(0.88,0.2),
        legend.background = element_rect(fill = NA)) #+
ggsave('PI_scatter.jpg',Fig1, width = 7.5, height = 5.0, dpi = 400)
```

```{r}
Fig1
```

