---
title: "Supermarket Data Analysis"
output: html_document
date: "2024-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='hide'}
path = dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(path)
library(MASS) 
library(ggplot2)
library(glmnet)
library(ggthemes)
library(patchwork)
library(doSNOW)
library(foreach)
library(doParallel)
source('Functions.R')
cl <- makeCluster(20, outfile = 'market_outs.out')
registerDoParallel(cl)
registerDoSNOW(cl)
clusterEvalQ(cl = cl, RhpcBLASctl::blas_set_num_threads(1))
Rep_times = 50
market = scale(as.matrix(read.csv('market.csv',header= F)))
parameter_q = seq(0.1,0.2,0.01)
Y = as.matrix(market[,1])
X_matrix0 = market[,2:6399]
corr = cor(Y, X_matrix0)
cut = sort(corr,decreasing = T)[1500]
X_matrix = X_matrix0[,which(corr >= cut)]



  
DD_inclusion0 = S_inclusion0 = SPlus_inclusion0 = Smin_inclusion0 = array(0,dim = c(length(parameter_q), ncol(X_matrix)))

Output_number <- foreach (time = 1:Rep_times, .packages =c('MASS', 'glmnet')) %dopar%  {
  source('Functions.R')
  set.seed(time+222)
  DD_inclusion = S_inclusion = SPlus_inclusion = Smin_inclusion = array(0,dim = c(length(parameter_q), ncol(X_matrix)))
  n = nrow(X_matrix)
  sample_index1 = sample(n,n/2)
  X_matrix1 = X_matrix[sample_index1,]
  sample_index2 = setdiff(c(1:n), sample_index1)
  X_matrix2 = X_matrix[sample_index2,]
  Y1 = Y[sample_index1,]
  Y2 = Y[sample_index2,]
  cvfit <- cv.glmnet(X_matrix, Y)
  lambda <- cvfit$lambda.min*1.2
  beta1 <- as.vector(glmnet(X_matrix1, Y1, alpha = 1, lambda = lambda)$beta)
  beta2 <- as.vector(glmnet(X_matrix2, Y2, alpha = 1, lambda = lambda)$beta)
  index_beta1 = which(beta1 == 0)
  index_beta2 = which(beta2 == 0)
  
  M1 = get_M(X_matrix1)
  M2 = get_M(X_matrix2)
  
  beta1_d = as.numeric(beta1 + 2/n*M1%*%t(X_matrix1)%*%(Y1 - X_matrix1 %*% beta1))
  beta2_d = as.numeric(beta2 + 2/n*M2%*%t(X_matrix2)%*%(Y2 - X_matrix2 %*% beta2))
  
  sigma1 = sqrt(diag(M1%*%(t(X_matrix1)%*%diag(diag((Y1-X_matrix1%*%beta1)%*%t(Y1-X_matrix1%*%beta1)))%*%X_matrix1/(n/2))%*%t(M1)))
  sigma2 = sqrt(diag(M2%*%(t(X_matrix2)%*%diag(diag((Y2-X_matrix2%*%beta2)%*%t(Y2-X_matrix2%*%beta2)))%*%X_matrix2/(n/2))%*%t(M2)))
  
  X1 = beta1_d/sigma1
  X2 = beta2_d/sigma2
  
  index1 = intersect(which(X1>0),which(X2>0))
  index2 = intersect(which(X1<0),which(X2>0))
  index3 = intersect(which(X1<0),which(X2<0))
  index4 = intersect(which(X1>0),which(X2<0))
  index13 = c(index1,index3)
  
  X1_4444 = c(X1[c(index2,index4)])
  X2_4444 = c(X2[c(index2,index4)])
  
  h0 = 1*c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
  h1 = 1.4*c(bandwidth.nrd(X1), bandwidth.nrd(X2))
  
  Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
  f0_hat0 = function(x){
    return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
  }
  f0_hat = function(x){
    return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
  }
  
  Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
  f_hat = function(x){
    return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
  }
  
  Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
  lfdr_points13 = apply(cbind(X1[c(index1,index3)],X2[c(index1,index3)]), 1, Lfdr_hat13)
  lfdr_points_2= apply(cbind(c(X1[index2],-X1[index2]),c(-X2[index2], X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
  lfdr_points_4= apply(cbind(c(-X1[index4],X1[index4]),c(X2[index4], -X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
  
  S_tol = X1*X2
  SPlus_tol = sign(X1*X2)*(abs(X1) + abs(X2))
  Smin_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
  
  number_table = matrix(0,nrow=11, ncol = 4)
  for (i in 1:length(parameter_q)) {
    q_loc_fdr = parameter_q[i]
    sh = get_conventional_threshold(S_tol,q_loc_fdr,1)
    number_times = length(which(S_tol >= sh))
    S_inclusion[i,which(S_tol >= sh)] = S_inclusion[i,which(S_tol >= sh)] + 1/max(number_times,1)
    
    sh = get_conventional_threshold(SPlus_tol,q_loc_fdr,1)
    number_plus = length(which(SPlus_tol >= sh))
    SPlus_inclusion[i,which(SPlus_tol >= sh)] = SPlus_inclusion[i,which(SPlus_tol >= sh)] + 1/max(number_plus,1)
    
    sh = get_conventional_threshold(Smin_tol,q_loc_fdr,1)
    number_min= length(which(Smin_tol >= sh))
    Smin_inclusion[i,which(Smin_tol >= sh)] = Smin_inclusion[i,which(Smin_tol >= sh)] + 1/max(number_min,1)
    
    fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, q_loc_fdr,1)
    number_adp = length(which(lfdr_points13<=fdr_q))
    DD_inclusion[i,index13[which(lfdr_points13<=fdr_q)]] = DD_inclusion[i,index13[which(lfdr_points13<=fdr_q)]] + 1/max(number_adp,1)
    
    number_table[i,] = c(number_adp, number_times, number_plus, number_min)
  }

  return(list(number_table, DD_inclusion, S_inclusion, SPlus_inclusion, Smin_inclusion))
}

discovery_table = discovery_table0 = matrix(0,11,4)
sigma_table = matrix(0,11,4)
for (i in 1:Rep_times) {
  discovery_table = discovery_table + Output_number[[i]][[1]]/Rep_times
  DD_inclusion0 = DD_inclusion0 + Output_number[[i]][[2]]/Rep_times
  S_inclusion0 = S_inclusion0 + Output_number[[i]][[3]]/Rep_times
  SPlus_inclusion0 = SPlus_inclusion0 + Output_number[[i]][[4]]/Rep_times
  Smin_inclusion0 = Smin_inclusion0 + Output_number[[i]][[5]]/Rep_times
}
for (i in 1:length(parameter_q)) {
  discovery_table0[i,1] = MSAS_Sup(DD_inclusion0[i,],parameter_q[i])
  discovery_table0[i,2] = MSAS_Sup(S_inclusion0[i,],parameter_q[i])
  discovery_table0[i,3] = MSAS_Sup(SPlus_inclusion0[i,],parameter_q[i])
  discovery_table0[i,4] = MSAS_Sup(Smin_inclusion0[i,],parameter_q[i])
}
discovery_table = round(discovery_table,digits=1)
discovery_table1 = as.character(discovery_table)
discovery_table01 = as.character(discovery_table0)
for (i in 1:Rep_times) {
  sigma_table = sigma_table + (Output_number[[i]][[1]] - discovery_table)^2/(Rep_times-1)
}
sigma_table = round((sigma_table/Rep_times)^0.5, digits=1)
sigma_table1 = paste('(',sigma_table,')',sep='')

plot_data1 = data.frame(Number=as.vector(discovery_table), Number1=as.vector(discovery_table1), Number2=as.vector(sigma_table1), FDR = factor(rep(parameter_q,4)), Method = factor(rep(c('SAS', 'DM', 'DSA', 'DSM'), each =  length(parameter_q)),levels=c('SAS', 'DM', 'DSA', 'DSM'), labels = c('SAS', 'DM', 'DSA', 'DSM')))

plot_data0 = data.frame(Number=as.vector(discovery_table0), Number1=as.vector(discovery_table01), FDR = factor(rep(parameter_q,4)), Method = factor(rep(c('SAS', 'DM', 'DSA', 'DSM'), each =  length(parameter_q)),levels=c('SAS', 'DM', 'DSA', 'DSM'), labels = c('SAS', 'DM', 'DSA', 'DSM')))

Fig = ggplot(data = plot_data1, aes(x=FDR,y=Number,fill=Method)) +
  geom_bar(stat="identity",position = position_dodge(0.8),width = 0.5, alpha = 0.5, color = 'gray') + 
  scale_fill_manual(values =c('#F8766D','#7CAE00','#00BFC4','#C77CFF')) +
  geom_text(aes(x=FDR,y=Number, label=Number1),position = position_dodge(0.8),size=2.2) +
  geom_text(aes(x=FDR,y=Number-1.8, label=Number2),position = position_dodge(0.8),size=1.8) +
  xlab(expression(q)) + 
  ylab('Number of discoveries')+
  theme_bw()  +
  theme(legend.position = c(0.1,0.8),
        legend.title = element_blank(),
        legend.box.background = element_blank(),
        legend.background = element_rect(fill=rgb(1,1,1,alpha=0.001),colour=NA))
ggsave('Market_bar_twosides_1.jpg',Fig, width = 9, height = 4, dpi = 400)

Fig0 = ggplot(data = plot_data0, aes(x=FDR,y=Number,fill=Method)) +
  geom_bar(stat="identity",position = position_dodge(0.8),width = 0.5, alpha = 0.5, color = 'gray') + 
  scale_fill_manual(values =c('#F8766D','#7CAE00','#00BFC4','#C77CFF')) +
  geom_text(aes(x=FDR,y=Number, label=Number1),position = position_dodge(0.8),size=2.2) +
  xlab(expression(q)) + 
  ylab('Number of discoveries')+
  ylim(c(0,100)) +
  theme_bw()  +
  theme(legend.position = c(0.1,0.8),
        legend.title = element_blank(),
        legend.box.background = element_blank(),
        legend.background = element_rect(fill=rgb(1,1,1,alpha=0.001),colour=NA))
ggsave('DER_Market_bar_twosides_1.jpg',Fig0, width = 9, height = 4, dpi = 400)

```

```{r, fig.width = 9, fig.height = 4}
Fig 
Fig0
```



```{r, results='hide'}
DD_inclusion0 = S_inclusion0 = SPlus_inclusion0 = Smin_inclusion0 = array(0,dim = c(length(parameter_q), ncol(X_matrix)))

Output_number <- foreach (time = 1:Rep_times, .packages =c('MASS', 'glmnet')) %dopar%  {
  source('Functions.R')
  set.seed(time+222)
  DD_inclusion = S_inclusion = SPlus_inclusion = Smin_inclusion = array(0,dim = c(length(parameter_q), ncol(X_matrix)))
  n = nrow(X_matrix)
  sample_index1 = sample(n,n/2)
  X_matrix1 = X_matrix[sample_index1,]
  sample_index2 = setdiff(c(1:n), sample_index1)
  X_matrix2 = X_matrix[sample_index2,]
  Y1 = Y[sample_index1,]
  Y2 = Y[sample_index2,]
  cvfit <- cv.glmnet(X_matrix, Y)
  lambda <- cvfit$lambda.min*1.2
  beta1 <- as.vector(glmnet(X_matrix1, Y1, alpha = 1, lambda = lambda)$beta)
  beta2 <- as.vector(glmnet(X_matrix2, Y2, alpha = 1, lambda = lambda)$beta)
  index_beta1 = which(beta1 == 0)
  index_beta2 = which(beta2 == 0)
  
  M1 = get_M(X_matrix1)
  M2 = get_M(X_matrix2)
  
  beta1_d = as.numeric(beta1 + 2/n*M1%*%t(X_matrix1)%*%(Y1 - X_matrix1 %*% beta1))
  beta2_d = as.numeric(beta2 + 2/n*M2%*%t(X_matrix2)%*%(Y2 - X_matrix2 %*% beta2))
  
  sigma1 = sqrt(diag(M1%*%(t(X_matrix1)%*%diag(diag((Y1-X_matrix1%*%beta1)%*%t(Y1-X_matrix1%*%beta1)))%*%X_matrix1/(n/2))%*%t(M1)))
  sigma2 = sqrt(diag(M2%*%(t(X_matrix2)%*%diag(diag((Y2-X_matrix2%*%beta2)%*%t(Y2-X_matrix2%*%beta2)))%*%X_matrix2/(n/2))%*%t(M2)))
  
  X1 = beta1_d/sigma1
  X2 = beta2_d/sigma2
  
  index1 = intersect(which(X1>0),which(X2>0))
  index2 = intersect(which(X1<0),which(X2>0))
  index3 = intersect(which(X1<0),which(X2<0))
  index4 = intersect(which(X1>0),which(X2<0))
  index13 = c(index1,index3)

  X1_4444 = c(X1[c(index2,index4)])
  X2_4444 = c(X2[c(index2,index4)])
  
  h0 = 1.0*c(bandwidth.nrd(X1_4444), bandwidth.nrd(X2_4444))
  h1 = 1.4*c(bandwidth.nrd(X1), bandwidth.nrd(X2))
  
  Kernel_h0 = function(x){0.3*sum(dnorm((x[1] - X1_4444)/h0[1])*dnorm((x[2] - X2_4444)/h0[2]))/(h0[1]*h0[2]*length(X1_4444))}
  f0_hat0 = function(x){
    return(0.25*(Kernel_h0(x) + Kernel_h0(c(-x[1],x[2])) + Kernel_h0(c(x[1],-x[2])) + Kernel_h0(-x)))
  }
  f0_hat = function(x){
    return(0.5*(f0_hat0(x) + f0_hat0(c(x[2],x[1]))))
  }
  
  Kernel_h1 = function(x){sum(dnorm((x[1] - X1)/h1[1])*dnorm((x[2] - X2)/h1[2]))/(h1[1]*h1[2]*length(X1))}
  f_hat = function(x){
    return(0.5*(Kernel_h1(x) + Kernel_h1(c(x[2],x[1]))))
  }
  
  Lfdr_hat13 = function(x){min(1,(f0_hat(x)/f_hat(x)))}
  lfdr_points_2 = rep(1,length(index2))
  lfdr_points_4 = rep(1,length(index4))
  lfdr_points13 = lfdr_points13 = rep(1,length(c(index1)))
  lfdr_points13 = apply(cbind(X1[c(index1)],X2[c(index1)]), 1, Lfdr_hat13)
  lfdr_points_2= apply(cbind(c(-X1[index2]),c(X2[index2])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
  lfdr_points_4= apply(cbind(c(X1[index4]),c(-X2[index4])), 1, function(x){min(1,f0_hat(x)/f_hat(x))})
  
  get_conventional_threshold <- function(S, q_loc_fdr){
    t = sort(abs(S))
    Ta = sapply(t,function(x){(1+0.5*length(S[S<(-x)]))/max(1,length(S[which(S>x & X1 >0)]))})
    sh = min(t[which(Ta<=q_loc_fdr)]) 
    return(sh)
  }
  
  S_tol = X1*X2
  SPlus_tol = sign(X1*X2)*(abs(X1) + abs(X2))
  Smin_tol = 2*sign(X1*X2)*apply(cbind(abs(X1), abs(X2)), 1, min)
  
  number_table = matrix(0,nrow=11, ncol = 4)
  for (i in 1:length(parameter_q)) {
    q_loc_fdr = parameter_q[i]
    sh = get_conventional_threshold(S_tol,q_loc_fdr)
    number_times = length(which((S_tol > sh) & (X1 >0)))
    S_inclusion[i,which((S_tol >= sh) & (X1 >0))] = S_inclusion[i,which((S_tol >= sh) & (X1 >0))] + 1/max(number_times,1)
    
    sh = get_conventional_threshold(SPlus_tol,q_loc_fdr)
    number_plus = length(which((SPlus_tol > sh) & (X1 >0)))
    SPlus_inclusion[i,which((SPlus_tol >= sh) & (X1 >0))] = SPlus_inclusion[i,which((SPlus_tol >= sh) & (X1 >0))] + 1/max(number_plus,1)
    
    sh = get_conventional_threshold(Smin_tol,q_loc_fdr)
    number_min= length(which((Smin_tol > sh)& (X1 >0)))
    Smin_inclusion[i,which((Smin_tol >= sh) & (X1 >0))] = Smin_inclusion[i,which((Smin_tol >= sh) & (X1 >0))] + 1/max(number_min,1)
    
    fdr_q = get_localfdr_threshold_half(lfdr_points13, lfdr_points_2, lfdr_points_4, q_loc_fdr, 1)
    number_adp = length(which(lfdr_points13<=fdr_q))
    DD_inclusion[i,index13[which(lfdr_points13<=fdr_q)]] = DD_inclusion[i,index13[which(lfdr_points13<=fdr_q)]] + 1/max(number_adp,1)
    
    number_table[i,] = c(number_adp, number_times, number_plus, number_min)
  }
  return(list(number_table, DD_inclusion, S_inclusion, SPlus_inclusion, Smin_inclusion))
}

discovery_table = discovery_table0 = matrix(0,11,4)
sigma_table = matrix(0,11,4)
for (i in 1:Rep_times) {
  discovery_table = discovery_table + Output_number[[i]][[1]]/Rep_times
  DD_inclusion0 = DD_inclusion0 + Output_number[[i]][[2]]/Rep_times
  S_inclusion0 = S_inclusion0 + Output_number[[i]][[3]]/Rep_times
  SPlus_inclusion0 = SPlus_inclusion0 + Output_number[[i]][[4]]/Rep_times
  Smin_inclusion0 = Smin_inclusion0 + Output_number[[i]][[5]]/Rep_times
}
for (i in 1:length(parameter_q)) {
  discovery_table0[i,1] = MSAS_Sup(DD_inclusion0[i,],parameter_q[i])
  discovery_table0[i,2] = MSAS_Sup(S_inclusion0[i,],parameter_q[i])
  discovery_table0[i,3] = MSAS_Sup(SPlus_inclusion0[i,],parameter_q[i])
  discovery_table0[i,4] = MSAS_Sup(Smin_inclusion0[i,],parameter_q[i])
}
discovery_table = round(discovery_table,digits=1)
discovery_table1 = as.character(discovery_table)
discovery_table01 = as.character(discovery_table0)
for (i in 1:Rep_times) {
  sigma_table = sigma_table + (Output_number[[i]][[1]] - discovery_table)^2/(Rep_times-1)
}
sigma_table = round((sigma_table/Rep_times)^0.5, digits=1)
sigma_table1 = paste('(',sigma_table,')',sep='')

plot_data1 = data.frame(Number=as.vector(discovery_table), Number1=as.vector(discovery_table1), Number2=as.vector(sigma_table1), FDR = factor(rep(parameter_q,4)), Method = factor(rep(c('SAS', 'DM', 'DSA', 'DSM'), each =  length(parameter_q)),levels=c('SAS', 'DM', 'DSA', 'DSM'), labels = c('SAS', 'DM', 'DSA', 'DSM')))

plot_data0 = data.frame(Number=as.vector(discovery_table0), Number1=as.vector(discovery_table01), FDR = factor(rep(parameter_q,4)), Method = factor(rep(c('SAS', 'DM', 'DSA', 'DSM'), each =  length(parameter_q)),levels=c('SAS', 'DM', 'DSA', 'DSM'), labels = c('SAS', 'DM', 'DSA', 'DSM')))

Fig = ggplot(data = plot_data1, aes(x=FDR,y=Number,fill=Method)) +
  geom_bar(stat="identity",position = position_dodge(0.8),width = 0.45, alpha = 0.5, color = 'gray') + 
  scale_fill_manual(values =c('#F8766D','#7CAE00','#00BFC4','#C77CFF')) +
  geom_text(aes(x=FDR,y=Number, label=Number1),position = position_dodge(0.8),size=1.6) +
  geom_text(aes(x=FDR,y=Number-1.8, label=Number2),position = position_dodge(0.8),size=1.3) +
  xlab(expression(q)) + 
  ylab('Number of discoveries')+
  coord_cartesian(ylim = c(13, 50)) +
  theme_bw()  +
  theme(legend.position = c(0.1,0.8),
        legend.title = element_blank(),
        legend.box.background = element_blank(),
        legend.background = element_rect(fill=rgb(1,1,1,alpha=0.001),colour=NA))
ggsave('Market_bar_oneside_1.jpg',Fig, width = 9, height = 4, dpi = 400)

Fig0 = ggplot(data = plot_data0, aes(x=FDR,y=Number,fill=Method)) +
  geom_bar(stat="identity",position = position_dodge(0.8),width = 0.5, alpha = 0.5, color = 'gray') + 
  scale_fill_manual(values =c('#F8766D','#7CAE00','#00BFC4','#C77CFF')) +
  geom_text(aes(x=FDR,y=Number, label=Number1),position = position_dodge(0.8),size=2.2) +
  xlab(expression(q)) + 
  ylab('Number of discoveries')+
  coord_cartesian(ylim = c(25, 105)) +
  theme_bw()  +
  theme(legend.position = c(0.1,0.8),
        legend.title = element_blank(),
        legend.box.background = element_blank(),
        legend.background = element_rect(fill=rgb(1,1,1,alpha=0.001),colour=NA))
ggsave('DER_Market_bar_oneside_1.jpg',Fig0, width = 9, height = 4, dpi = 400)
```

```{r, fig.width = 9, fig.height = 4}
Fig 
```
```{r, fig.width = 9, fig.height = 4}
Fig0 
```


```{r, results='hide'}
##### Scatter plot ####
set.seed(1)
n = nrow(X_matrix)
sample_index1 = sample(n,n/2)
X_matrix1 = X_matrix[sample_index1,]
sample_index2 = setdiff(c(1:n), sample_index1)
X_matrix2 = X_matrix[sample_index2,]
Y1 = Y[sample_index1,]
Y2 = Y[sample_index2,]
cvfit <- cv.glmnet(X_matrix, Y)
lambda <- cvfit$lambda.min*1.2
beta1 <- as.vector(glmnet(X_matrix1, Y1, alpha = 1, lambda = lambda)$beta)
beta2 <- as.vector(glmnet(X_matrix2, Y2, alpha = 1, lambda = lambda)$beta)
index_beta1 = which(beta1 == 0)
index_beta2 = which(beta2 == 0)

M1 = get_M(X_matrix1)
M2 = get_M(X_matrix2)

beta1_d = as.numeric(beta1 + 2/n*M1%*%t(X_matrix1)%*%(Y1 - X_matrix1 %*% beta1))
beta2_d = as.numeric(beta2 + 2/n*M2%*%t(X_matrix2)%*%(Y2 - X_matrix2 %*% beta2))

sigma1 = sqrt(diag(M1%*%(t(X_matrix1)%*%diag(diag((Y1-X_matrix1%*%beta1)%*%t(Y1-X_matrix1%*%beta1)))%*%X_matrix1/(n/2))%*%t(M1)))
sigma2 = sqrt(diag(M2%*%(t(X_matrix2)%*%diag(diag((Y2-X_matrix2%*%beta2)%*%t(Y2-X_matrix2%*%beta2)))%*%X_matrix2/(n/2))%*%t(M2)))

X1 = beta1_d/sigma1
X2 = beta2_d/sigma2
plot_lim = 0.75
plot_data = data.frame(X1,X2)

scat_plot1 <- ggplot(plot_data) +
  geom_point(aes(X1 ,X2), fill="#8ea0cc",shape=21,  alpha = 0.4 , size =1.5) +
  theme_bw() +
  xlab(expression(italic(t^(1))))+
  ylab(expression(italic(t^(2))))+
  ylim(c(-plot_lim,plot_lim)) +
  xlim(c(-plot_lim,plot_lim)) + 
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.7) +
  geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.7) 
ggsave('Market_scatter.jpg',scat_plot1, width = 6, height = 6, dpi = 400)
stopImplicitCluster()
stopCluster(cl)
```

```{r, fig.width = 6, fig.height = 6}
scat_plot1
```
